### ISSUE TITLE
Python lib error on armv5 borg 1.0.9 binary

### ISSUE THREAD

**Issue by jjsaas** [bauerj/borg-binaries#1]
The error message is:

Error loading Python lib '/tmp/_MEIKrQnWN/libpython3.5m.so.1.0': /lib/libc.so.6: version `GLIBC_2.7' not found (required by /tmp/_MEIKrQnWN/libpython3.5m.so.1.0)

**Comment by bauerj** [comment]
Thank you for reporting this bug.

A few questions:
- What OS are you trying to run this on? glibc 2.7 is really old (10 years now).
- Does/did it work with borg 1.0.7?

**Comment by jjsaas** [comment]
This is on qnap 212 nas hardware.
Linux QNAPNAS212 3.4.6 Wed Dec 14 10:22:56 CST 2016 armv5tel unknown
Processor name  : Feroceon 88F6281 rev 1 (v5l) @ 1.2 GHz

borg 1.0.7 also fails with the same error.

**Comment by bauerj** [comment]
Can you tell me what glibc version is installed? `ldd --version`

**Comment by jjsaas** [comment]
here it is ...

ldd --version
ldd (GNU libc) 2.5
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by bauerj** [comment]
Wow, that *is* old. 

I would need to get a system with that specific version to build a compatible binary. I don't think that's worth the effort considering the system is more than 10 years old. Sorry :/

**Comment by jjsaas** [comment]
oh okay. Is there a way I can try to build it on that machine?

**Comment by bauerj** [comment]
Sure, you just need to install Python 3.5 and pip first:

https://borgbackup.readthedocs.io/en/stable/installation.html#pip-installation
