### ISSUE TITLE
Missing armv5 1.1.8 build

### ISSUE THREAD

**Issue by ernierasta** [bauerj/borg-binaries#11]
Hi,
probably armv5 failed to build again? Can you look at this?

Thank you!

**Comment by bauerj** [comment]
Hey,

thanks for reporting. @noplanman did a great job on rewriting the buildchain. I'll change my website to host the binaries produced by his builders soon. In the meantime, can you try this one? 

https://dl.bintray.com/noplanman/borg-binaries/

**Comment by noplanman** [comment]
@ernierasta Repo has moved:
https://dl.bintray.com/borg-binary-builder/borg-binaries/

**Comment by ernierasta** [comment]
thank you! Are you planing to update https://borg.bauerj.eu/?

I am asking, because I would like to implement binary autoupgrade, so I am currently checking this page, hopefully not overusing it by downloading html page once per day.

**Comment by bauerj** [comment]
Yes. I can also provide a JSON interface if you'd like.

**Comment by ernierasta** [comment]
Would be great! :+1:

**Comment by bauerj** [comment]
You can find it here: https://borg.bauerj.eu/binaries.json
