### ISSUE TITLE
Binaries for borg 1.2.4 are empty

### ISSUE THREAD

**Issue by Rilele** [bauerj/borg-binaries#12]
All three binaries for borg 1.2.4. on https://borg.bauerj.eu/ are empty.

The JSON at https://borg.bauerj.eu/binaries.json ist also empty and the link https://git.feneas.org/borg-binary-builder/borg-binaries in the section "Where can I submit bug reports or feature requests?" is also dead.

**Comment by bauerj** [comment]
Thank you, I've changed the link for bug reports.

I've also deleted the empty 1.2.4 files and re-triggered the build. I hope it will be fixed in a few hours.

**Comment by bauerj** [comment]
The binaries are working now ☺
