### ISSUE TITLE
Binaries for arm64

### ISSUE THREAD

**Issue by noplanman** [bauerj/borg-binaries#2]
Would be nice to have a binary built for arm64 devices (e.g. Pine64) 😊

**Comment by bauerj** [comment]
Sure, I'll look into it 👍

**Comment by bauerj** [comment]
It seems like the setup I'm using for armv5/armv6 won't work with arm64. Can you tell me what glibc version you are using?

    ldd --version

**Comment by noplanman** [comment]
```bash
# ldd --version
ldd (Debian GLIBC 2.19-18+deb8u7) 2.19
```
Is that all you need?

**Comment by bauerj** [comment]
Yes, thank you!

**Comment by noplanman** [comment]
@bauerj Any progress on this? :innocent:

**Comment by bauerj** [comment]
Sorry, I know it has been nearly a year without any progress but this seems to be more complicated than I initially thought. The build process randomly crashes and I couldn't find out why.

**Comment by noplanman** [comment]
Do you have your build scripts public somewhere so I can also give it a try?
I have very little experience, but sometimes it helps to have another set of eyes :innocent:

**Comment by kBite** [comment]
Have you looked at SynoCommunity's approach? There is some progress in building a borgbackup spk package: https://github.com/SynoCommunity/spksrc/issues/2351

**Comment by noplanman** [comment]
@kBite Awesome, thanks for sharing that! Would love to see it running on my DS too :smiley: 

Was already prepared to simply use sshfs to make the link, but a "native" package would be all too perfect!

**Comment by bauerj** [comment]
Hey,

sure, I can upload the build scripts (although I need to clean them up a bit first). However, you would have to manually install Debian (or Raspbian) wheezy into a QEMU VM in order to use them. I guess for arm64 some newer OS could be used but that would raise the minimum supported glibc/kernel version.

I don't have any documentation how I installed the VMs but there are some instructions on the internet.

**Comment by noplanman** [comment]
@bauerj That would be much appreciated, thanks :ok_hand:

**Comment by bauerj** [comment]
Alright, I checked in the scripts but be warned that this requires a significant amount of work to set up 😕

**Comment by noplanman** [comment]
@kBite You mentioned that you have a DS218play, which is `armv8`, not `arm64`.

Have you tried just getting the borg v6 binary from here? Not sure if it works for v8 too though.
https://borg.bauerj.eu/

(or do you have some other `arm64` server around too?)

**Comment by kBite** [comment]
rtd1296 (ARMv8.0-A) has 4x Cortex-A53 which support `aarch64` (https://developer.arm.com/products/processors/cortex-a/cortex-a53). Refering to https://stackoverflow.com/a/47274698 `arm64` and `aarch64` seem synonymous. `armv8`, `aarch64`, and `arm64` are also handled as synonymous by FreeBSD:
> FreeBSD/arm64 is the FreeBSD port to the 64-bit ARM architecture, also known as AArch64 or ARMv8.
- https://wiki.freebsd.org/arm64

I don't have other `arm64` hardware - does RasPi3 with A53 cores count ;)?

I never hassled with cross-compilation. Is there any difference between `armv8`, `aarch64`, and `arm64` when building binaries?

**Comment by noplanman** [comment]
Right, thanks for your response!

Clearly my ignorance got the best of me, proving again that assumptions aren't good :grin: 

Looking at the links you've sent me, it just showed me how little I know about all this architecture stuff and how vast it all is!

(At this point a huge "Thanks!" to everybody who does the leg work to make it all so much more pleasant for us users :pray:)

**Back to the topic:**

You should be able to get the official [SynoCommunity Borg package](https://synocommunity.com/package/borgbackup).

You'll need to build your own Python 3 package though, as it's not updated by SynoCommunity yet, have a look here:
https://github.com/borgbackup/borg/issues/719#issuecomment-383416325

**Comment by noplanman** [comment]
I'm obviously very new to this building/compiling stuff and thus enter with a certain "noobz-brain".

@bauerj Have you tried this docker image for building by any chance?
https://hub.docker.com/r/arm64v8/python/

**Comment by noplanman** [comment]
Closing here due to https://git.feneas.org/noplanman/borg-binary-builder
