### ISSUE TITLE
Package for systems with uClibc

### ISSUE THREAD

**Issue by friesenkiwi** [bauerj/borg-binaries#3]
Hi,
thank you for your efforts in providing ARM builds!

I am in the process of setting up a custom backup solution based on the D-Link DNS-320L (ARM5) with the Alt-F Firmware (https://sites.google.com/site/altfirmware/) and want to use borgbackup for this. The current packages don't work, because Alt-F uses [uClibc](https://www.uclibc.org/about.html) instead of glibc. Do you think, it would be possible to build a package for that?

Thanks in advance for considering,
Cheers

**Comment by bauerj** [comment]
Hey!

It should be possible to create such a package but it would probably require a lot of work. I would have to recompile all the libraries and Python itself. I don't think it would be worth the effort.

If you're able to install Python 3.6 on your system, take a look at [Installation ➡️ From Source](https://borgbackup.readthedocs.io/en/stable/installation.html#from-source) to find out how to install Borg.

**Comment by friesenkiwi** [comment]
The Python 3.6 is exactly the problem, unfortunately. Currently there is only a 2.7.2 package available.
Judging from https://github.com/borgbackup/borg/issues/1018#issuecomment-231549938 you are kind of on the same path as me in building a custom backup NAS solution?

I am not yet very literate in C/C++ or in Python or in embedded systems/cross compiling/buildroot/replacing libcs, but I am eager to make this work and learn on the way. If you think, it could be feasible and maybe help out with answering some questions along the way, I am considering to go down that path and spend the effort, at least try to fathom how much effort it really is.

**Comment by bauerj** [comment]
> Currently there is only a 2.7.2 package available.

It should be relatively easy to compile a more recent version of Python directly on the device.

> you are kind of on the same path as me in building a custom backup NAS solution?

Kind of. I'm running borg on a NAS.

> If you think, it could be feasible and maybe help out with answering some questions along the way, I am considering to go down that path and spend the effort, at least try to fathom how much effort it really is.

Sure, if you have any questions just let me know!

**Comment by friesenkiwi** [comment]
> It should be relatively easy to compile a more recent version of Python directly on the device.
Huh, I hope so, but there are a couple of dependencies more listed on borg's page ... I'll see if I can manage to try next week.

Thanks already.

**Comment by Neustradamus** [comment]
@friesenkiwi: For information:

Note that D-Link DNS-320L and DNS-325 are supported in OpenWrt:
- https://github.com/openwrt/openwrt/pull/17924
- https://github.com/openwrt/openwrt/pull/16803
- https://github.com/openwrt/openwrt/pull/15433
